apiVersion: v2
name: netbird
description: A Helm chart to deploy self-hosted NetBird
type: application
version: 1.1.4
appVersion: "0.77.0"
dependencies:
    -   name: postgresql
        version: 18.8.13
        repository: oci://registry-1.docker.io/bitnamicharts
        condition: postgresql.enabled
