apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
    name: {{ include "paperless.workerName" . }}
    namespace: {{ include "common.names.namespace" . | quote }}
    {{- $labels := include "common.tplvalues.merge" ( dict "values" ( list .Values.worker.labels .Values.commonLabels ) "context" . ) }}
    labels: {{- include "common.labels.standard" (dict "customLabels" $labels "context" $) | nindent 8 }}
        app.kubernetes.io/component: worker
    {{- if or .Values.commonAnnotations .Values.worker.annotations }}
    {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.worker.annotations .Values.commonAnnotations ) "context" . ) }}
    annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 8 }}
    {{- end }}
spec:
    replicas: {{ include "paperless.workerReplicaCount" . }}
    strategy:
        type: {{ include "paperless.workerStrategyType" . }}
    selector:
        {{- $podLabels := include "common.tplvalues.merge" ( dict "values" ( list .Values.worker.podLabels .Values.commonLabels ) "context" . ) }}
        matchLabels: {{- include "common.labels.matchLabels" (dict "customLabels" $podLabels "context" $) | nindent 12 }}
            app.kubernetes.io/component: worker
    template:
        metadata:
            labels: {{- include "common.labels.standard" (dict "customLabels" $podLabels "context" $) | nindent 16 }}
                app.kubernetes.io/component: worker
            {{- if .Values.worker.podAnnotations }}
            annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.worker.podAnnotations "context" $ ) | nindent 16 }}
            {{- end }}
        spec:
            {{- include "paperless.imagePullSecrets" . | nindent 12 }}
            serviceAccountName: {{ include "paperless.serviceAccountName" . }}
            {{- if .Values.worker.podSecurityContext.enabled }}
            securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.worker.podSecurityContext "context" $) | nindent 16 }}
            {{- end }}
            initContainers: {{- include "paperless.waitForCore" . | nindent 16 }}
            containers:
                -   name: worker
                    image: {{ include "paperless.image" . | quote }}
                    imagePullPolicy: {{ .Values.image.pullPolicy }}
                    command:
                        - celery
                        - --app
                        - paperless
                        - worker
                        - --loglevel
                        - INFO
                    {{- if .Values.worker.containerSecurityContext.enabled }}
                    securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.worker.containerSecurityContext "context" $) | nindent 24 }}
                    {{- end }}
                    env: {{- include "paperless.baseEnv" . | nindent 24 }}
                        -   name: PAPERLESS_OCR_MODE
                            value: {{ .Values.config.ocr.mode | quote }}
                        -   name: PAPERLESS_MEDIA_ROOT
                            value: {{ .Values.persistence.media.mountPath | quote }}
                        -   name: PAPERLESS_CONSUMPTION_DIR
                            value: {{ .Values.persistence.consume.mountPath | quote }}
                        -   name: PAPERLESS_SCRATCH_DIR
                            value: {{ include "paperless.scratchPath" . | quote }}
                        -   name: PAPERLESS_OCR_LANGUAGE
                            value: {{ join "+" .Values.config.ocr.languages | quote }}
                        {{- if .Values.core.tika.enabled }}
                        -   name: PAPERLESS_TIKA_ENABLED
                            value: "1"
                        -   name: PAPERLESS_TIKA_ENDPOINT
                            value: "http://{{ include "paperless.tikaServiceName" . }}:{{ .Values.core.tika.service.port }}"
                        {{- if .Values.core.gotenberg.enabled }}
                        -   name: PAPERLESS_TIKA_GOTENBERG_ENDPOINT
                            value: "http://{{ include "paperless.gotenbergServiceName" . }}:{{ .Values.core.gotenberg.service.port }}"
                        {{- end -}}
                        {{- end -}}
                        {{- if .Values.worker.extraEnvVars }}
                        {{- include "common.tplvalues.render" (dict "value" .Values.worker.extraEnvVars "context" $) | nindent 24 }}
                        {{- end }}
                    resources: {{- toYaml .Values.worker.resources | nindent 24 }}
                    volumeMounts: {{- include "paperless.baseVolumeMounts" . | nindent 24 }}
                        -   name: media
                            mountPath: {{ .Values.persistence.media.mountPath }}
                            {{- if .Values.persistence.media.subPath }}
                            subPath: {{ .Values.persistence.media.subPath }}
                            {{- end }}
                        -   name: consume
                            mountPath: {{ .Values.persistence.consume.mountPath }}
                            {{- if .Values.persistence.consume.subPath }}
                            subPath: {{ .Values.persistence.consume.subPath }}
                            {{- end }}
                        {{- range $lang := .Values.config.ocr.installLanguages }}
                        -   name: data
                            mountPath: {{ printf "%s/%s.traineddata" (include "paperless.tessdataPath" .) $lang }}
                            subPath: {{ printf "%s/tessdata/%s.traineddata" (default "" $.Values.persistence.data.subPath) $lang | trimPrefix "/" }}
                        {{- end }}
                        -   name: worker-tmp
                            mountPath: /tmp
                        {{- if .Values.worker.extraVolumeMounts }}
                        {{- include "common.tplvalues.render" (dict "value" .Values.worker.extraVolumeMounts "context" $) | nindent 24 }}
                        {{- end }}
            volumes: {{- include "paperless.volumes" (dict "volumes" (list "data" "media" "consume") "context" $) | indent 16 }}
                -   name: wait-tmp
                    emptyDir: { }
                -   name: worker-tmp
                    emptyDir: { }
                {{- if .Values.worker.extraVolumes }}
                {{- include "common.tplvalues.render" ( dict "value" .Values.worker.extraVolumes "context" $ ) | nindent 16 }}
                {{- end }}
            {{- if .Values.worker.affinity }}
            affinity: {{- include "common.tplvalues.render" (dict "value" .Values.worker.affinity "context" $) | nindent 16 }}
            {{- end }}
            {{- if .Values.worker.nodeSelector }}
            nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.worker.nodeSelector "context" $) | nindent 16 }}
            {{- end }}
            {{- if .Values.worker.tolerations }}
            tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.worker.tolerations "context" $) | nindent 16 }}
            {{- end }}