apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
    name: {{ include "paperless.coreName" . }}
    namespace: {{ include "common.names.namespace" . | quote }}
    {{- $labels := include "common.tplvalues.merge" ( dict "values" ( list .Values.core.labels .Values.commonLabels ) "context" . ) }}
    labels: {{- include "common.labels.standard" (dict "customLabels" $labels "context" $) | nindent 8 }}
        app.kubernetes.io/component: core
    {{- if or .Values.commonAnnotations .Values.core.annotations }}
    {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.core.annotations .Values.commonAnnotations ) "context" . ) }}
    annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 8 }}
    {{- end }}
spec:
    replicas: 1
    strategy:
        type: Recreate
    selector:
        {{- $podLabels := include "common.tplvalues.merge" ( dict "values" ( list .Values.core.podLabels .Values.commonLabels ) "context" . ) }}
        matchLabels: {{- include "common.labels.matchLabels" (dict "customLabels" $podLabels "context" $) | nindent 12 }}
            app.kubernetes.io/component: core
    template:
        metadata:
            labels: {{- include "common.labels.standard" (dict "customLabels" $podLabels "context" $) | nindent 16 }}
                app.kubernetes.io/component: core
            {{- if .Values.core.podAnnotations }}
            annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.core.podAnnotations "context" $ ) | nindent 16 }}
            {{- end }}
        spec:
            {{- include "paperless.imagePullSecrets" . | nindent 12 }}
            serviceAccountName: {{ include "paperless.serviceAccountName" . }}
            {{- if .Values.core.podSecurityContext.enabled }}
            securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.core.podSecurityContext "context" $) | nindent 16 }}
            {{- end }}
            initContainers:
                {{- if .Values.config.ocr.installLanguages }}
                -   name: init-tesseract-langs
                    image: {{ include "paperless.image" . | quote }}
                    {{- if .Values.core.fetchOcr.containerSecurityContext.enabled }}
                    securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.core.fetchOcr.containerSecurityContext "context" $) | nindent 24 }}
                    {{- end }}
                    command: [ "/scripts/init-tesseract-langs.sh" ]
                    env:
                        -   name: PAPERLESS_OCR_LANGUAGES
                            value: {{ join " " .Values.config.ocr.installLanguages | quote }}
                        {{- if .Values.core.fetchOcr.extraEnvVars }}
                        {{- include "common.tplvalues.render" (dict "value" .Values.core.fetchOcr.extraEnvVars "context" $) | nindent 24 }}
                        {{- end }}
                    resources: {{- toYaml .Values.core.fetchOcr.resources | nindent 24 }}
                    volumeMounts:
                        -   name: init-scripts
                            mountPath: /scripts
                            readOnly: true
                        -   name: data
                            mountPath: {{ .Values.persistence.data.mountPath }}
                            {{- if .Values.persistence.data.subPath }}
                            subPath: {{ .Values.persistence.data.subPath }}
                            {{- end }}
                        {{- if .Values.core.fetchOcr.extraVolumeMounts }}
                        {{- include "common.tplvalues.render" (dict "value" .Values.core.fetchOcr.extraVolumeMounts "context" $) | nindent 24 }}
                        {{- end }}
                {{- end }}
                -   name: init
                    image: {{ include "paperless.image" . | quote }}
                    imagePullPolicy: {{ .Values.image.pullPolicy }}
                    command: [ "/scripts/init.sh" ]
                    {{- if .Values.core.init.containerSecurityContext.enabled }}
                    securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.core.init.containerSecurityContext "context" $) | nindent 24 }}
                    {{- end }}
                    env: {{- include "paperless.baseEnv" . | nindent 24 }}
                        -   name: USER_IS_NON_ROOT
                            value: "true"
                        -   name: PAPERLESS_OCR_LANGUAGE
                            value: {{ join "+" .Values.config.ocr.languages | quote }}
                        {{- if or .Values.config.createUser .Values.config.existingCredentialsSecret }}
                        -   name: PAPERLESS_ADMIN_USER
                            valueFrom:
                                secretKeyRef:
                                    name: {{ include "paperless.credentialsSecretName" . }}
                                    key: name
                        -   name: PAPERLESS_ADMIN_PASSWORD
                            valueFrom:
                                secretKeyRef:
                                    name: {{ include "paperless.credentialsSecretName" . }}
                                    key: password
                        -   name: PAPERLESS_ADMIN_MAIL
                            valueFrom:
                                secretKeyRef:
                                    name: {{ include "paperless.credentialsSecretName" . }}
                                    key: mail
                        {{- end }}
                        {{- if .Values.core.init.extraEnvVars }}
                        {{- include "common.tplvalues.render" (dict "value" .Values.core.init.extraEnvVars "context" $) | nindent 24 }}
                        {{- end }}
                    resources: {{- toYaml .Values.core.init.resources | nindent 24 }}
                    volumeMounts: {{- include "paperless.baseVolumeMounts" . | nindent 24 }}
                        -   name: init-scripts
                            mountPath: /scripts
                            readOnly: true
                        -   name: init-tmp
                            mountPath: /tmp
                        {{- range $lang := .Values.config.ocr.installLanguages }}
                        -   name: data
                            mountPath: {{ printf "%s/%s.traineddata" (include "paperless.tessdataPath" .) $lang }}
                            subPath: {{ printf "%s/tessdata/%s.traineddata" (default "" $.Values.persistence.data.subPath) $lang | trimPrefix "/" }}
                        {{- end }}
                        {{- if .Values.core.init.extraVolumeMounts }}
                        {{- include "common.tplvalues.render" (dict "value" .Values.core.init.extraVolumeMounts "context" $) | nindent 24 }}
                        {{- end }}
            containers:
                -   name: consumer
                    image: {{ include "paperless.image" . | quote }}
                    imagePullPolicy: {{ .Values.image.pullPolicy }}
                    command:
                        - python3
                        - manage.py
                        - document_consumer
                    {{- if .Values.core.consumer.containerSecurityContext.enabled }}
                    securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.core.consumer.containerSecurityContext "context" $) | nindent 24 }}
                    {{- end }}
                    env: {{- include "paperless.baseEnv" . | nindent 24 }}
                        -   name: PAPERLESS_CONSUMPTION_DIR
                            value: {{ .Values.persistence.consume.mountPath | quote }}
                        {{- if .Values.core.consumer.extraEnvVars }}
                        {{- include "common.tplvalues.render" (dict "value" .Values.core.consumer.extraEnvVars "context" $) | nindent 24 }}
                        {{- end }}
                    resources: {{- toYaml .Values.core.consumer.resources | nindent 24 }}
                    volumeMounts: {{- include "paperless.baseVolumeMounts" . | nindent 24 }}
                        -   name: consume
                            mountPath: {{ .Values.persistence.consume.mountPath }}
                            {{- if .Values.persistence.consume.subPath }}
                            subPath: {{ .Values.persistence.consume.subPath }}
                            {{- end }}
                        -   name: consumer-tmp
                            mountPath: /tmp
                        {{- if .Values.core.consumer.extraVolumeMounts }}
                        {{- include "common.tplvalues.render" (dict "value" .Values.core.consumer.extraVolumeMounts "context" $) | nindent 24 }}
                        {{- end }}
                -   name: scheduler
                    image: {{ include "paperless.image" . | quote }}
                    imagePullPolicy: {{ .Values.image.pullPolicy }}
                    command:
                        - celery
                        - --app
                        - paperless
                        - beat
                        - --loglevel
                        - INFO
                    {{- if .Values.core.scheduler.containerSecurityContext.enabled }}
                    securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.core.scheduler.containerSecurityContext "context" $) | nindent 24 }}
                    {{- end }}
                    env: {{- include "paperless.baseEnv" . | nindent 24 }}
                        {{- if .Values.core.scheduler.extraEnvVars }}
                        {{- include "common.tplvalues.render" (dict "value" .Values.core.scheduler.extraEnvVars "context" $) | nindent 24 }}
                        {{- end }}
                    resources: {{- toYaml .Values.core.scheduler.resources | nindent 24 }}
                    volumeMounts: {{- include "paperless.baseVolumeMounts" . | nindent 24 }}
                        -   name: scheduler-tmp
                            mountPath: /tmp
                        {{- if .Values.core.scheduler.extraVolumeMounts }}
                        {{- include "common.tplvalues.render" (dict "value" .Values.core.scheduler.extraVolumeMounts "context" $) | nindent 24 }}
                        {{- end }}
                {{- if .Values.core.gotenberg.enabled }}
                -   name: gotenberg
                    image: {{ include "paperless.gotenbergImage" . | quote }}
                    imagePullPolicy: {{ .Values.core.gotenberg.image.pullPolicy }}
                    command:
                        - gotenberg
                        - "--chromium-disable-javascript=true"
                        - "--chromium-allow-list=file:///tmp/.*"
                        - "--api-port={{ .Values.core.gotenberg.service.port }}"
                    {{- if .Values.core.gotenberg.containerSecurityContext.enabled }}
                    securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.core.gotenberg.containerSecurityContext "context" $) | nindent 24 }}
                    {{- end }}
                    ports:
                        -   name: gotenberg-http
                            containerPort: {{ .Values.core.gotenberg.service.port }}
                            protocol: TCP
                    {{- if .Values.core.gotenberg.extraEnvVars }}
                    env: {{- include "common.tplvalues.render" (dict "value" .Values.core.gotenberg.extraEnvVars "context" $) | nindent 24 }}
                    {{- end }}
                    {{- if .Values.core.gotenberg.startupProbe.enabled }}
                    startupProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.core.gotenberg.startupProbe "enabled") "context" $) | nindent 24 }}
                        httpGet:
                            path: /health
                            port: gotenberg-http
                    {{- end }}
                    {{- if .Values.core.gotenberg.livenessProbe.enabled }}
                    livenessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.core.gotenberg.livenessProbe "enabled") "context" $) | nindent 24 }}
                        httpGet:
                            path: /health
                            port: gotenberg-http
                    {{- end }}
                    {{- if .Values.core.gotenberg.readinessProbe.enabled }}
                    readinessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.core.gotenberg.readinessProbe "enabled") "context" $) | nindent 24 }}
                        httpGet:
                            path: /health
                            port: gotenberg-http
                    {{- end }}
                    resources: {{- toYaml .Values.core.gotenberg.resources | nindent 24 }}
                    volumeMounts:
                        -   name: gotenberg-tmp
                            mountPath: /tmp
                        {{- if .Values.core.gotenberg.extraVolumeMounts }}
                        {{- include "common.tplvalues.render" (dict "value" .Values.core.gotenberg.extraVolumeMounts "context" $) | nindent 24 }}
                        {{- end }}
                {{- end }}
                {{- if .Values.core.tika.enabled }}
                -   name: tika
                    image: {{ include "paperless.tikaImage" . | quote }}
                    ports:
                        -   containerPort: {{ .Values.core.tika.service.port }}
                            name: tika-http
                    {{- if .Values.core.tika.containerSecurityContext.enabled }}
                    securityContext: {{- include "common.compatibility.renderSecurityContext" (dict "secContext" .Values.core.tika.containerSecurityContext "context" $) | nindent 24 }}
                    {{- end }}
                    {{- if .Values.core.tika.extraEnvVars }}
                    env: {{- include "common.tplvalues.render" (dict "value" .Values.core.tika.extraEnvVars "context" $) | nindent 24 }}
                    {{- end }}
                    {{- if .Values.core.tika.startupProbe.enabled }}
                    startupProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.core.tika.startupProbe "enabled") "context" $) | nindent 24 }}
                        httpGet:
                            path: /
                            port: tika-http
                    {{- end }}
                    {{- if .Values.core.tika.livenessProbe.enabled }}
                    livenessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.core.tika.livenessProbe "enabled") "context" $) | nindent 24 }}
                        httpGet:
                            path: /
                            port: tika-http
                    {{- end }}
                    {{- if .Values.core.tika.readinessProbe.enabled }}
                    readinessProbe: {{- include "common.tplvalues.render" (dict "value" (omit .Values.core.tika.readinessProbe "enabled") "context" $) | nindent 24 }}
                        httpGet:
                            path: /
                            port: tika-http
                    {{- end }}
                    resources: {{- toYaml .Values.core.tika.resources | nindent 24 }}
                    volumeMounts:
                        -   name: tika-tmp
                            mountPath: /tmp
                        {{- if .Values.core.tika.extraVolumeMounts }}
                        {{- include "common.tplvalues.render" (dict "value" .Values.core.tika.extraVolumeMounts "context" $) | nindent 24 }}
                        {{- end }}
                {{- end }}
            volumes: {{- include "paperless.volumes" (dict "volumes" (list "data" "consume") "context" $) | indent 16 }}
                -   name: init-scripts
                    configMap:
                        name: {{ include "paperless.scriptsConfigName" . }}
                        defaultMode: 0755
                -   name: init-tmp
                    emptyDir: { }
                -   name: consumer-tmp
                    emptyDir: { }
                -   name: scheduler-tmp
                    emptyDir: { }
                -   name: gotenberg-tmp
                    emptyDir: { }
                -   name: tika-tmp
                    emptyDir: { }
                {{- if .Values.core.extraVolumes }}
                {{- include "common.tplvalues.render" ( dict "value" .Values.core.extraVolumes "context" $ ) | nindent 16 }}
                {{- end }}
            {{- if .Values.core.affinity }}
            affinity: {{- include "common.tplvalues.render" (dict "value" .Values.core.affinity "context" $) | nindent 16 }}
            {{- end }}
            {{- if .Values.core.nodeSelector }}
            nodeSelector: {{- include "common.tplvalues.render" (dict "value" .Values.core.nodeSelector "context" $) | nindent 16 }}
            {{- end }}
            {{- if .Values.core.tolerations }}
            tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.core.tolerations "context" $) | nindent 16 }}
            {{- end }}