{{- if not .Values.config.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
    name: {{ include "paperless.configSecretName" . }}
    namespace: {{ include "common.names.namespace" . | quote }}
    labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 8 }}
    {{- if or .Values.secretAnnotations .Values.commonAnnotations }}
    annotations:
        {{- if .Values.secretAnnotations }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.secretAnnotations "context" $ ) | nindent 8 }}
        {{- end }}
        {{- if .Values.commonAnnotations }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 8 }}
        {{- end }}
    {{- end }}
stringData:
    secretKey: {{ required "config.secretKey is required when no existingSecret is configured" .Values.config.secretKey | quote }}
{{- end }}
