{{- if and .Values.config.createUser (not .Values.config.existingCredentialsSecret) }}
apiVersion: v1
kind: Secret
metadata:
    name: {{ include "paperless.credentialsSecretName" . }}
    namespace: {{ include "common.names.namespace" . | quote }}
    labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 8 }}
        app.kubernetes.io/component: apiToken
    {{- if or .Values.secretAnnotations .Values.commonAnnotations }}
    annotations:
        {{- if .Values.secretAnnotations }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.secretAnnotations "context" $ ) | nindent 8 }}
        {{- end }}
        {{- if .Values.commonAnnotations }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 8 }}
        {{- end }}
    {{- end }}
stringData:
    mail: {{ required "config.credentials.mail is required when no existingCredentialsSecret is configured" .Values.config.credentials.mail | quote }}
    name: {{ required "config.credentials.name is required when no existingCredentialsSecret is configured" .Values.config.credentials.name | quote }}
    password: {{ required "config.credentials.password is required when no existingCredentialsSecret is configured" .Values.config.credentials.password | quote }}
{{- end }}
