{{- if and (eq (include "paperless.databaseMode" .) "external") (not .Values.config.database.external.existingSecret) .Values.config.database.external.password -}}
apiVersion: v1
kind: Secret
metadata:
    name: {{ include "paperless.databasePasswordSecretName" . }}
    namespace: {{ include "common.names.namespace" . | quote }}
    labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 8 }}
    {{- if or .Values.secretAnnotations .Values.commonAnnotations }}
    annotations:
        {{- if .Values.secretAnnotations }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.secretAnnotations "context" $ ) | nindent 8 }}
        {{- end }}
        {{- if .Values.commonAnnotations }}
        {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 8 }}
        {{- end }}
    {{- end }}
type: Opaque
stringData:
    password: {{ .Values.config.database.external.password | quote }}
{{- end -}}