apiVersion: v1
kind: Service
metadata:
    name: {{ include "paperless.webServerName" . }}
    namespace: {{ include "common.names.namespace" . | quote }}
    {{- $labels := .Values.commonLabels }}
    {{- if .Values.webserver.service.labels }}
    {{- $labels = include "common.tplvalues.merge" ( dict "values" ( list .Values.webserver.service.labels $labels ) "context" . ) }}
    {{- end }}
    labels: {{- include "common.labels.standard" ( dict "customLabels" $labels "context" $ ) | nindent 8 }}
        app.kubernetes.io/component: webserver
    {{- if or .Values.commonAnnotations .Values.webserver.service.annotations }}
    {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.webserver.service.annotations .Values.commonAnnotations ) "context" . ) }}
    annotations: {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
    {{- end }}
spec:
    type: {{ .Values.webserver.service.type }}
    ports:
        -   name: http
            targetPort: http
            protocol: TCP
            port: {{ .Values.webserver.service.port }}
    {{- $podLabels := include "common.tplvalues.merge" ( dict "values" ( list .Values.core.podLabels .Values.commonLabels ) "context" . ) }}
    selector: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 8 }}
        app.kubernetes.io/component: webserver