{{- if not .Values.server.config.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
    name: {{ include "netbird.configSecretName" . }}
stringData:
    config.yaml: |
        server:
            listenAddress: ":{{ .Values.server.services.http.port }}"
            exposedAddress: "https://{{ include "netbird.domain" . }}:443"
            stunPorts:
                - {{ .Values.server.services.stun.port }}
            {{- if .Values.metrics.enabled }}
            metricsPort: {{ .Values.metrics.port }}
            {{- end }}
            healthcheckAddress: ":9000"
            logLevel: "info"
            logFile: "console"

            authSecret: {{ include "netbird.authSecret" . | quote }}
            dataDir: {{ printf "%s/" (.Values.server.persistence.mountPath | trimSuffix "/") | quote }}

            auth:
                issuer: "https://{{ include "netbird.domain" . }}/oauth2"
                signKeyRefreshEnabled: true
                dashboardRedirectURIs:
                    - "https://{{ include "netbird.domain" . }}/nb-auth"
                    - "https://{{ include "netbird.domain" . }}/nb-silent-auth"
                cliRedirectURIs:
                    - "http://localhost:53000/"

            reverseProxy:
                trustedHTTPProxies:
                    {{- toYaml .Values.trustedHTTPProxies | nindent 20 }}

            {{- $databaseMode := include "netbird.databaseMode" . -}}
            store:
                {{- if eq $databaseMode "sqlite" }}
                engine: "sqlite"
                encryptionKey: {{ include "netbird.encryptionKey" . | quote }}
                {{- else if eq $databaseMode "postgresql" }}
                engine: "postgres"
                postgres:
                    host: {{ include "netbird.databaseHost" . | quote }}
                    port: {{ .Values.server.database.external.port }}
                    database: {{ .Values.server.database.external.name | quote }}
                    user: {{ include "netbird.databaseUser" . | quote }}
                    password: {{ include "netbird.databasePassword" . | quote }}
                    sslmode: {{ .Values.server.database.external.sslMode | quote }}
                {{- else if eq $databaseMode "external" }}
                engine: {{ .Values.server.database.external.engine | quote }}
                {{- if .Values.server.database.external.dsn }}
                {{ .Values.server.database.external.engine }}:
                    dsn: {{ .Values.server.database.external.dsn | quote }}
                {{- else }}
                {{ .Values.server.database.external.engine }}:
                    host: {{ .Values.server.database.external.host | quote }}
                    port: {{ .Values.server.database.external.port }}
                    database: {{ .Values.server.database.external.name | quote }}
                    user: {{ .Values.server.database.external.username | quote }}
                    password: {{ include "netbird.databaseExternalPassword" . | quote }}
                    {{- if eq .Values.server.database.external.engine "postgres" }}
                    sslmode: {{ .Values.server.database.external.sslMode | quote }}
                    {{- end }}
                {{- end }}
                {{- end }}
{{- with .Values.server.config.extraYaml }}
{{ . | nindent 12 }}
{{- end }}
{{- end }}