{{- if not .Values.config.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
    name: {{ include "netbird.configSecretName" . }}
stringData:
    config.yaml: |
        server:
            listenAddress: ":{{ .Values.server.services.http.port }}"
            exposedAddress: "https://{{ include "netbird.domain" . }}:443"
            stunPorts:
                - {{ .Values.server.services.stun.port }}
            {{- if .Values.metrics.enabled }}
            metricsPort: {{ .Values.metrics.port }}
            {{- end }}
            healthcheckAddress: ":9000"
            logLevel: "info"
            logFile: "console"

            authSecret: {{ include "netbird.authSecret" . | quote }}
            dataDir: {{ printf "%s/" (.Values.server.persistence.mountPath | trimSuffix "/") | quote }}

            auth:
                issuer: {{ include "netbird.authIssuer" . | quote }}
                signKeyRefreshEnabled: true
                dashboardRedirectURIs:
                    - "https://{{ include "netbird.domain" . }}/nb-auth"
                    - "https://{{ include "netbird.domain" . }}/nb-silent-auth"
                cliRedirectURIs:
                    - "http://localhost:53000/"
                {{- if or (and .Values.config.auth.owner.email .Values.config.auth.owner.password) .Values.config.auth.owner.existingSecret }}
                owner:
                    email: {{ include "netbird.authOwnerEmail" . | quote }}
                    password: {{ include "netbird.authOwnerPassword" . | quote }}
                {{- end }}

            reverseProxy:
                trustedHTTPProxies: {{- toYaml .Values.config.trustedHTTPProxies | nindent 20 }}
            store:
                engine: {{ include "netbird.storeEngine" . | quote }}
                dsn: {{ include "netbird.storeConfigDsn" . | quote }}
                encryptionKey: {{ include "netbird.storeEncryptionKey" . | quote }}
{{- with .Values.config.extraYaml }}
{{ . | nindent 12 }}
{{- end }}
{{- end }}