{{- if not .Values.server.config.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
    name: {{ include "netbird.configSecretName" . }}
stringData:
    config.yaml: |
        server:
            listenAddress: ":{{ .Values.server.services.http.port }}"
            exposedAddress: "https://{{ include "netbird.domain" . }}:443"
            stunPorts:
                - {{ .Values.server.services.stun.port }}
            {{- if .Values.metrics.enabled }}
            metricsPort: {{ .Values.metrics.port }}
            {{- end }}
            healthcheckAddress: ":9000"
            logLevel: "info"
            logFile: "console"

            authSecret: {{ include "netbird.authSecret" . | quote }}
            dataDir: {{ printf "%s/" (.Values.server.persistence.mountPath | trimSuffix "/") | quote }}

            auth:
                issuer: "https://{{ include "netbird.domain" . }}/oauth2"
                signKeyRefreshEnabled: true
                dashboardRedirectURIs:
                    - "https://{{ include "netbird.domain" . }}/nb-auth"
                    - "https://{{ include "netbird.domain" . }}/nb-silent-auth"
                cliRedirectURIs:
                    - "http://localhost:53000/"

            reverseProxy:
                trustedHTTPProxies:
                    {{- toYaml .Values.trustedHTTPProxies | nindent 20 }}
            store:
                engine: {{ include "netbird.storeEngine" . | quote }}
                dsn: {{ include "netbird.storeConfigDsn" . | quote }}
{{- with .Values.server.config.extraYaml }}
{{ . | nindent 12 }}
{{- end }}
{{- end }}