apiVersion: v1
kind: Service
metadata:
    name: {{ include "netbird.stunServiceName" . }}
    labels:
        {{- include "netbird.labels" . | nindent 8 }}
        app.kubernetes.io/component: server
spec:
    type: {{ .Values.server.services.stun.type }}
    ports:
        -   name: stun
            targetPort: stun
            protocol: UDP
            port: {{ .Values.server.services.stun.port }}
    selector:
        {{- include "netbird.componentSelectorLabels" (dict "root" . "component" "server") | nindent 8 }}