{{- if and .Values.gateway.enabled (not .Values.ingress.enabled) -}}
{{- if .Capabilities.APIVersions.Has "gateway.networking.k8s.io/v1/GRPCRoute" -}}
apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
    name: {{ include "netbird.fullname" . }}-server-signal
    labels:
        {{- include "netbird.labels" . | nindent 8 }}
    {{- with .Values.gateway.annotations }}
    annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
spec:
    {{- with .Values.gateway.parentRefs }}
    parentRefs:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    hostnames:
        - {{ .Values.domain | quote }}
    rules:
        -   backendRefs:
                -   group: ''
                    kind: Service
                    name: {{ include "netbird.serverServiceName" . }}
                    port: {{ .Values.server.services.http.port }}
            matches:
                -   method:
                        type: Exact
                        service: signalexchange.SignalExchange
{{- end }}
{{- end }}